### ISSUE TITLE
HighSierra compatible?

### ISSUE THREAD

**Issue by josefrichter** [ricsxn/ShowQR#1]
Hi, is this supposed to work on High Sierra, please? Installed it, but cannot see it among services. Or maybe I just missed some installation steps? Thank you very much!

**Comment by ricsxn** [comment]
I knew about this issue but I never tried to fix it because I personally lost interest on this tool.
I developed this little utility because I needed to move small text strings from my personal computer to my mobile device. Today this activity can be done via WhatsApp web or using Apple shared clipboard.
However I identified the matter, since I wrongly used directory /System/Library to deploy the ShowQR service. I also fixed the Package creation moving from the no longer supported PackageMaker to the Packages application.
I tested the new package installation on MacOSX 10.13.2 (High Sierra) and it is working fine.
